version: '3.9'
services: 
  jenkins:
    image: jenkins/jenkins:lts
    container_name: "jenkins"
    ports:
      - '8080:8080'
      - '443:443'
      - '50000:50000'
    volumes:
      - ./srv/data/jenkins_date:/jenkins_home
      - ./srv/data/jenkins:/var/jenkins_config

